name: SolidSkies
main: co.matrixdevelopment.solidskies.SolidSkies
version: ${project.version}
api-version: 1.13
description: A skyblock plugin, everything more, nothing less
commands:
  sa:
    description: The Solid Skies admin command
    usage: /sa <subcommand>