name: Solid-Skies
main: co.matrixdevelopment.solidskies.SolidSkies
version: 0.0.5
api-version: 1.13
description: A skyblock plugin
commands:
  sa:
    description: The Solid Skies admin command
    usage: /sa <subcommand>